# Generated by Django 2.2.5 on 2020-01-25 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200125_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='books.Book'),
        ),
    ]
